[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "software_challenge_client"
version = "0.0.1"
authors = [
  { name="FalconsSky", email="stu222782@mail.uni-kiel.de" },
]
description = "This is the package for the Software-Challenge Germany 2023. This Season the game will be 'Hey, danke für den Fisch' a.k.a. 'Penguins' in short."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU LGPLv3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"